# Simple workflow for deploying content to GitHub Pages
name: Deploy content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # invoke npm build command to build contents
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
          cache: npm
      - name: Run the "npm install" command
        run: npm ci
      - name: Run the "npm run build" command
        run: npm run build     
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_site' 
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
