name: Cypress tests
on: push
jobs:
  cypress-run:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: Start server in the background
        run: npm start
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run >/dev/null