name: Cypress tests
on: push
jobs:
  branches:
    - '*'
    - '!main'
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Start server in the background
        run: npm start &
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js