name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
        run: npm ci
      - name: Start server in the background
        run: npm start
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          build: npm run build
          command: npx cypress run >/dev/null