name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install root dependencies
        run: npm ci
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          # Cancel the run after 2 failed tests
          auto-cancel-after-failures: 2
          build: npm run build
          start: npm start
          config-file: cypress.config.js